version: "3.9"
services:
  mongo:
    image: mongo
    restart: always
    container_name: mongo-clients
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: secret
    ports:
      - 27017:27017