version: "3.9"
services:
  client:
    build: ./client
    container_name: pagodevs-clients
    ports:
      - 3001:3001
    depends_on:
      - mongo
  mongo:
    image: mongo
    restart: always
    container_name: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: secret
    ports:
      - 27017:27017



