openapi: 3.0.3
info:
  title: Client API
  description: API responsible for client data in a fraud detection context.
  version: 1.0.0
  contact: 
    name: Berguem Paula Almdeia, Cairo Gonçalves Ribeiro, Daniel Duarte, Karina Brandão Pimenta, Patrick Escorsi Silva, Roberto Tetsuo Helney e Thayara Nathalia Siqueira 
    email: pagodevs@pagonxt.com
paths: 
  /v1/clients/verify: 
    get: 
        summary: Card Data validation
        description: We receive the card data and validate it by making comparisons in the DB. 
        responses: 
          200:
            description: "Sucesso"
            content: 
              application/json:
                schema:
                    $ref: "#/components/schemas/SuccessNumberCard"
          400: 
            description: Bad Request
            content: 
              application/json:
                schema:
                    $ref: "#/components/schemas/FailNumberCard"
          404: 
            description: Card not found
            content: 
              application/json:
                example: "Not Found!"
  /v1/clients/{id}:
    get:
      summary: Finding Client
      description: We receive the client's id and return his personal data, without card data.
      parameters: 
      - name: id
        in: path
        schema: 
          type: string
        required: true
      responses: 
        200:
          description: "Sucesso"
          content: 
            application/json:
              schema:
                $ref: "#/components/schemas/SuccessFindById"
        404: 
          description: Client not found
          content: 
            application/json:
              example: "Not Found!"
components: 
  schemas:
    Address: 
      type: object
      properties:
        street:
          type: string
        number:
          type: string
        complement:
          type: string
        zipCode:
          type: string
          pattern: '^\d{5}-?\d{3}$'
        city:
          type: string
        state:
          type: string
          pattern: '(A[CLMP]|BA|CE|DF|ES|GO|M[AGST]|P[ABEIR]|R[JNORS]|S[CEP]|TO)'
    Card:
      type: object
      properties:
        numberCard:
          type: string
          minLength: 16
          maxLength: 16
          pattern: '\d{16}'
        name:
          type: string
        expirationDate:
          type: string
          pattern: '\d{4}-\d{2}'
        cvv:
          type: string
          minLength: 3
          maxLength: 3
          pattern: '\d{3}'
        dueDate:
          type: integer
          minimum: 1
          maximum: 31
    Client:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        cpf:
          type: string
          minLength: 11
          maxLength: 14
          pattern: '\d{3}\.?\d{3}\.?\d{3}-?\d{2}'
        email:
          type: string
          format: email
        telephone:
          type: string
          pattern: '^\(?[1-9]{2}\)? ?(?:[2-8]|9[1-9])\d{3}-?\d{4}$'
        monthlyIncome:
          type: number
          minimum: 0
        adress:
          $ref: '#/components/schemas/Address'
        cardData:
          $ref: '#/components/schemas/Card'
    SuccessNumberCard: 
      type: object
      properties:
        message: 
          type: string
        _id:
          type: string
        monthlyIncome: 
          type: number
    FailNumberCard: 
      type: object
      properties:
        message: 
          type: string
        _id:
          type: string
          nullable: true
        monthlyIncome: 
          type: number
          nullable: true
    SuccessFindById: 
      type: object
      properties:
        message: 
          type: string
        name:
          type: string
        cpf:
          type: string
          pattern: '\d{3}\.\*{3}\.\*{3}-\*{2}'
        numberCard: 
          type: string
          pattern: '\d{3}\*{13}'
        