openapi: 3.0.1
info:
  title: Transactions
  version: 0.0.1
  contact:
    name: PagoDevs
paths:
  /v1/transaction/{id}:
    get:
      summary: Find the transaction
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Transaction'
        '404':
          description: No data entered
          content:
            application/json:
              example: Transaction not Found
    patch:
      summary: Update the status
      responses:
        '204':
          description: Success
        '404':
          description: No data entered
          content:
            application/json:
              example: Transaction not Found
        '400':
          description: Incorrect data
          content:
            application/json:
              example: Change not allowed
  /v1/transaction:
    post:
      summary: Create a transaction
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Transaction'
components:
  schemas:
    Transaction:
      type: object
      properties:
        _id:
          type: string
        amount:
          type: number
        idCliente:
          type: string
        status:
          type: string
        cardData:
          type: object
          properties:
            name:
              type: string
            numberCard:
              type: string
            expirationDate:
              type: string
            cvc:
              type: string
